### PR TITLE
regular maintenance

### PR DESCRIPTION
**Pull request by zhaow-de**
* feat: added Ansible Galaxy collection community docker (https://github.com/ringier-data/ops-ci-aws/issues/13)
* chore: regular dependencies updates

### CODE REVIEW

**Comment by zhaow-de** [comment]
@aartaria could you please have a look at `requirements.txt`? This is the newest result of the dependencies resolution. I see some major version updates there, e.g.:
* `dvc[s3]==2.58.2` => `dvc[s3]==3.2.2`
* `dvc-data==0.51.0` => `dvc-data==2.3.0`

**Comment by zhaow-de** [comment]
@davidecantoni could you please check if the Iris codebase works with 18.16.1 (was 18.16.0)?

**Comment by zhaow-de** [comment]
@thecopy this is only FYI. To prevent a potential total-fuxk-up by Docker Inc., @aartaria is piloting to work only with Rancher Desktop as the local `containerd` frontend for local development activities. With this PR he introduced a new role parameter to explicitly tell `docker-buildx` to build the image for the specified platforms. During the exercise, he discovered another issue that does not apply to our Docker Desktop users. All fixed in https://github.com/ringier-data/ops-ci-aws/pull/14. When we introduced our own custom image for CodeBuild, the Ansible Galaxy collections are baked into the image, so that we need to deploy this repo to make his changes the default for all repos.

**Comment by aartaria** [comment]
> @aartaria could you please have a look at `requirements.txt`? This is the newest result of the dependencies resolution. I see some major version updates there, e.g.:
> 
> * `dvc[s3]==2.58.2` => `dvc[s3]==3.2.2`
> * `dvc-data==0.51.0` => `dvc-data==2.3.0`

@zhaow-de reading the release notes it looks it shouldn't make a difference, since 
* we are not using any of the deprecated features
* 3.x is compatible with 2.x cache and we never commit any dvc file from Codebuild so it should not break for projects based on 2.x

**Review by davidecantoni — APPROVED** [review]
Those changes are compatible with Iris.

**Pull request merged**
